import { useState } from "react";
import Head from "next/head";
import Sidebar from "../components/Sidebar";

export default function Home() {
  const [displaySideBar, setDisplaySideBar] = useState(true);
  return (
    <div className="bg-[url('https://sm.mashable.com/t/mashable_in/photo/default/1c68081b-1534-4be3-9fec-3ba599fe525f_pvjx.1248.jpg')] bg-no-repeat bg-cover h-screen flex justify-center">
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar
        displaySideBar={displaySideBar}
        setDisplaySideBar={setDisplaySideBar}
      />
      <div className="bg-white rounded-xl shadow-xl px-14 py-8 h-24 mt-20">
        <div
          onClick={() => setDisplaySideBar(true)}
          className="bg-gradient-to-r from-sky-200 to-green-400 hover:from-sky-300 hover:to-green-500 rounded-full px-5 py-2 cursor-pointer h-12 w-18 inline-block"
        >
          Start a chat!
        </div>
      </div>
    </div>
  );
}
